linters-settings:
  staticcheck:
    checks:
      - all
      # Exclude some staticcheck messages
      - '-SA1008' # "content-length" is not canonical
      - '-SA1019' # deprecations, deprecation warnings
run:
  timeout: 5m
